### ISSUE TITLE
GFM Tables do not work properly

### ISSUE THREAD

**Issue by styfle** [bevacqua/domador#1] opened 2015-06-03 01:44 UTC
Here are the steps to reproduce on the demo page http://bevacqua.github.io/woofmark/
#### Click markdown icon and paste the following

``` markdown
| col1 | col2 | col3 |
|------|------|------|
| foo  | bar  | baz  |
| food | bars | bats |
```
#### Click wysiwyg icon and you'll see a table (woohoo!) but without borders (boo)

| col1 | col2 | col3 |
| --- | --- | --- |
| foo | bar | baz |
| food | bars | bats |
#### Click html icon and you'll see proper html table (woohoo!)

``` html
<table>
<thead>
<tr><th>col1</th><th>col2</th><th>col3</th></tr>
</thead>
<tbody>
<tr><td>foo</td><td>bar</td><td>baz</td></tr>
<tr><td>food</td><td>bars</td><td>bats</td></tr>
</tbody>
</table>
```
#### Now click markdown icon and you'll get paragraphs?? (oops)

```
col1col2col3

foobarbaz

foodbarsbats
```

I'm assuming the html -> markdown doesn't support tables yet?

**Comment by bevacqua** [comment] 2015-06-03 01:45
This sounds about right. We should implement HTML table -> GFM table in domador. Can you look into it?

**Comment by styfle** [comment] 2015-06-03 01:47
@bevacqua Maybe on the weekend but I don't have much free time. Just enough time to read this comment :sweat_smile:

**Comment by sbruchmann** [comment] 2016-01-31 03:56
Is anybody currently working on this? I’d like to contribute this feature but I won’t promise anything :blush:

cc @bevacqua @bevacqua

**Comment by bevacqua** [comment] 2016-02-03 01:35
@sbruchmann Sorry for the late reply. I'm just looking at the issue now but I haven't gotten to it at all. It shouldn't be super hard to do in `domador`, but there's things we won't be able to support (such as alignment)

**Comment by bevacqua** [comment] 2016-02-03 03:52
Making progress here FWIW :)

**Comment by sbruchmann** [comment] 2016-02-03 03:55
Sounds great! :+1:

**Comment by bevacqua** [comment] 2016-02-03 04:02
Passing

``` js
test('about tables', function (t) {
  t.equal(domador(`<table>
    <thead>
    <tr>
    <th>colu1</th>
    <th>colum2</th>
    <th>column3</th>
    </tr>
    </thead>
    <tbody>
    <tr>
    <td>foo</td>
    <td>bar</td>
    <td>baz</td>
    </tr>
    <tr>
    <td>food</td>
    <td>bars</td>
    <td>bats</td>
    </tr>
    </tbody>
    </table>`),
`| colu1 | colum2 | column3 |
|-------|--------|---------|
| foo   | bar    | baz     |
| food  | bars   | bats    |`);
  t.end();
});
```

**Comment by bevacqua** [comment] 2016-02-03 05:00
Also passing _(harder due to how little context `domador` kept track of)_

``` js
test('about tables with complex content', function (t) {
  t.equal(domador(`<table>
    <thead>
    <tr>
    <th>colu1</th>
    <th><strong>colum2</strong></th>
    <th>column3</th>
    </tr>
    </thead>
    <tbody>
    <tr>
    <td>foo</td>
    <td><em>bar</em></td>
    <td>baz</td>
    </tr>
    <tr>
    <td>food</td>
    <td>bars</td>
    <td>bats</td>
    </tr>
    </tbody>
    </table>`),
`| colu1 | **colum2** | column3 |
|-------|------------|---------|
| foo   | _bar_      | baz     |
| food  | bars       | bats    |`);
  t.end();
});
```

**Comment by bevacqua** [comment] 2016-02-03 05:16
Released as `2.2.0`! :dancer:

**Comment by sbruchmann** [comment] 2016-02-03 05:17
Woah, this is amazing! Thank you very much!

**Comment by bevacqua** [comment] 2016-02-03 05:20
There still seems to be an issue preventing this from working properly in `woofmark` though. Investigating.

The example code turns into:

```
| col1 | col2 | col3 ||------|------|------|| foo  | bar  | baz  || food | bars | bats |
```

I suspect something trims out the `\n` line endings for some reason.

**Comment by bevacqua** [comment] 2016-02-03 05:22
Ah also integrated with CI btw

**Comment by bevacqua** [comment] 2016-02-03 05:42
Ah, it fails when browserified!

**Comment by bevacqua** [comment] 2016-02-03 06:06
Okay `2.2.1` fixes it. That was a weird bug.

**Comment by bevacqua** [comment] 2016-02-03 06:06
https://github.com/bevacqua/domador/commit/a61a5438aea25e51ebbed94769086914926ed1a7

**Closed as completed by bevacqua** 2016-02-03 06:06 UTC

**Comment by jywarren** [comment] 2016-05-11 16:33
Hmm, I'm using domador 2.3.0 in Woofmark, and seeing this:

```
* simple to make
* ease of use
* low cost

| col1 | col2 | col3 |
|------|------|------|
| foo  | bar  | baz  |
| food | bars | bats |
```

convert into tables, but when I convert back to markdown, it loses some newlines:

```
* simple to make
* ease of use
* low cost| col1 | col2 | col3 |
|------|------|------|
| foo  | bar  | baz  |
|      | food | bars |
```

Shall I try to write a test for domador to reproduce this?

**Comment by jywarren** [comment] 2016-05-11 16:33
and/or open a new issue?

**Comment by jywarren** [comment] 2016-05-23 16:50
I've written a test for this, and opened a PR for it at #3.
